### PR TITLE
Update contributors

### PR DESCRIPTION
**Pull request by guybedford**
@lookfirst @Zoltu @smehrbrodt @swirlycheetah @vladima @jschultzmn @smastous @MadLittleMods @johnraz @JoshAntBrown 

Thanks everyone for your contributions to the project. I've updated the contributors file with your details for this release. Please let me know if you'd like to be removed or have your details changed here before merge.

### CODE REVIEW

**Comment by swirlycheetah** [comment]
Thanks @guybedford, I'm looking forward to hopefully contributing more in the future.

**Comment by JoshAntBrown** [comment]
:+1: Thanks @guybedford, looking forward to contributing more in future too.

**Comment by MadLittleMods** [comment]
Thank you @guybedford  :grinning:

**Comment by vladima** [comment]
@guybedford thanks!

**Comment by jschultzmn** [comment]
Thanks @guybedford, pleasure working on such a great project.

**Comment by johnraz** [comment]
@guybedford  Thanks !

**Pull request merged**
