### PR TITLE
chore(coverage): add cover info through istanbul

### PR DESCRIPTION
**Pull request by douglasduteil**
Run `npm run coverage` will run the coverage with HTML output.

TODO: Use the [travis hook](http://docs.travis-ci.com/user/code-climate/#JavaScript) to publish the coverage on Code Climate. (tips https://coderwall.com/p/5mtq6q/encrypt-your-code-climate-repo-token-for-public-repositories-on-travis-ci)

### CODE REVIEW

**Comment by guybedford** [comment]
Nice! Thanks so much for your help again here. I just tried running this but it hangs on:

```
> jspm@0.15.3 coverage /Users/guybedford/Projects/jspm-cli
> npm run istanbul -- --report html


> jspm@0.15.3 istanbul /Users/guybedford/Projects/jspm-cli
> istanbul cover ./node_modules/.bin/_mocha --report html
```

Any idea how I would go about debugging this?

**Comment by douglasduteil** [comment]
Hum it's actually working https://travis-ci.org/jspm/jspm-cli/jobs/57930509#L245 
but that's right... it takes a hell of a time...
Maybe the scope of files to process for future coverage is to large sry...

**Comment by douglasduteil** [comment]
:up: Adding restriction on `lib/**/*.js` files

**Comment by guybedford** [comment]
Amazing, thanks. I've merged manually in https://github.com/jspm/jspm-cli/commit/d9488aa16391e0746e5706fde655a64088d30065.

Really appreciate your help with these test configurations @douglasduteil.

**Comment by douglasduteil** [comment]
You are welcome @guybedford :smile: 
I would love to contribute more to this project but I often run out of time...

<br/>

> Amazing, thanks. I've merged manually in d9488aa.

Would you like me to close this PR then?

**Pull request closed without merging**
