### PR TITLE
Expose the jspm version in the API

### PR DESCRIPTION
**Pull request by jackfranklin**
Couple of times I've written small tools in which I've wanted to just
log the current version of jspm.

@guybedford seemed like a sensible addition to me - what do you think?

### CODE REVIEW

**Comment by jackfranklin** [comment]
I added a test primarily so I had confidence that I had done it right, but the test seems pretty brittle to me, so if you'd like me to get rid of it I'm happy to!

**Comment by guybedford** [comment]
Looks great thanks Jack! A test is fine, let's just make it upgradable by doing `version.match(/\d+\.\d+\.\d+(-[^\.]+)?/)` or something like that?

**Comment by jackfranklin** [comment]
@guybedford perfect, updated :+1:

**Comment by guybedford** [comment]
:+1: (sorry just missed this one for the release!)

**Pull request merged**
