### PR TITLE
feat(pkg): jspm use bundled dependencies

### PR DESCRIPTION
**Pull request by douglasduteil**
Bundled dependencies makes JSPM installations more reliable (like npm).

### CODE REVIEW

**Comment by guybedford** [comment]
This is great!

I just worry about my local linked setup messing with this on npm publish. Is this reliable when the `node_modules` is a complete mess?

**Comment by douglasduteil** [comment]
Hum... Yes I guess.

**Comment by douglasduteil** [comment]
You could publish from fresh install.
Ensuring that the install and the test works before hand.

**Comment by douglasduteil** [comment]
My be using a shell script like :

```
cd ~/tmp
git clone https://github.com/jspm/jspm-cli.git --depth=1  --branch=0.17
cd jspm-cli
npm i
npm test
npm version 0.17.0-beta.20
npm publish
git push origin master && git push origin --tags
cd ..
rm -rf jspm-cli
```

**Comment by guybedford** [comment]
Closing for lack of activity. Feel free to reopen.

**Pull request closed without merging**
