### PR TITLE
Fixed typo regarding systemJS version range. Version now locked to 0.18.5

### PR DESCRIPTION
**Pull request by NicholasGW**

### CODE REVIEW

**Comment by NicholasGW** [comment]
Sorry, totally didn't read the contributing guide properly :).

**Comment by guybedford** [comment]
No problem, but thanks will sort this out with the next release.

**Comment by NicholasGW** [comment]
Thanks! For future reference if I try to fix something should I be submitting an MR to the contributors branch?

**Comment by guybedford** [comment]
We do run on master, that was a feature branch. This side I've already updated to SystemJS 0.16 but haven't pushed, so thought that's what you referring to.

**Pull request closed without merging**
