### PR TITLE
Downcase `name` and `target` inputs to jspm.install

### PR DESCRIPTION
**Pull request by jackfranklin**
To tackle #1274.

Not entirely sure how to write a test, so I didn't, but let me know @guybedford !

### CODE REVIEW

**Comment by guybedford** [comment]
Apologies, I forget that `target` is a PackageName class here (the comments are actually incorrect and should be removed, it is always an instance of this class).

We can probably just implement this as the first step in the PackageName class instantiation then - https://github.com/jspm/jspm-cli/blob/master/lib/config/package-name.js#L28.

**Comment by jackfranklin** [comment]
Thanks @guybedford ! So we should still downcase `name`, but move the downcasing of `target` into `PackageName` ?

**Comment by guybedford** [comment]
@jackfranklin I think we can skip downcasing `name` as it doesn't correspond to a file on the filesystem, which is where the casing conflicts occur.

**Comment by jackfranklin** [comment]
@guybedford can you take a second look? Updated.

**Comment by guybedford** [comment]
Looks great! :+1: to a +1 diff :)

**Pull request merged**
