### PR TITLE
Ability to specify a postinstall script in package.json's jspm.scripts.

### PR DESCRIPTION
**Pull request by trusktr**
For effect, it works. This one will conflict with https://github.com/jspm/jspm-cli/pull/370. One would have to be rebased after the other gets merged.

 Any considerations to consider or patterns I need to use?

### CODE REVIEW

**Comment by guybedford** [comment]
I really do not want to implement post-install scripts. Can you describe what use cases we need this for?

**Comment by trusktr** [comment]
Well, since my library doesn't have an entry point, I just want all the files in the root after install, so

```js
{
  "name": "infamous",
  // ...
  "jspm": {
    "scripts": {
      "postinstall": "mv src/* ./"
    }
  }
}
```

**Comment by guybedford** [comment]
This is what `directories.lib` is for.

**Comment by trusktr** [comment]
True, and it works fine for github repos. What about npm repos?

**Comment by guybedford** [comment]
So my argument is that we're aiming simply to match npm behaviour exactly in npm. If you were just using npm, you would have the same problem. So it is an npm problem not a jspm problem.

**Comment by trusktr** [comment]
But in npm I can solve this problem with a `postinstall` script that moves everything into the root. :D

In webpack, the problem is solved like this:

```js
// webpack.config.js
var webpack = require('webpack')
module.exports = {
    entry: "./src/app.js",
    output: {
        path: './public',
        filename: "app.js"
    },
    module: {
        loaders: [
            { test: /\.css$/, loader: "style!css" }
        ]
    },
    resolve: {
        alias: {
            famous: 'famous/src' // right here, this takes the src folder out of the way.
        }
    }
}
```

**Comment by trusktr** [comment]
Wait, isn't there something like this for jspm? A map?

**Comment by trusktr** [comment]
Something like 

```
{
  "map": {
    "infamous": "infamous/src"
  }
}
```

in the parent package?

**Comment by guybedford** [comment]
@trusktr ok that makes sense! So if we supported npm postinstall scripts that would cover this.

Note though another way to do this would be as a prepublish script that did the same thing, with a postpublish script that cleaned it up again. That would then work with jspm and npm.

You could also do a map like:

```json
{
  "map": {
    "./mainone": "./src/mainone"
  }
}
```

To generate these.

**Comment by guybedford** [comment]
@trusktr I appreciate allowing `directories.lib` here could be an option. What we could do is something like https://github.com/jspm/npm/issues/35.

**Comment by trusktr** [comment]
Where do the results of the `map` appear? WOuld they appear in `config.js`?

**Comment by guybedford** [comment]
* Relative local maps (like the above) create forwarding modules like we do for the main entry point.
* All other maps replace into require statements of that package.

**Comment by trusktr** [comment]
What about perhaps creating a new alias feature similar to webpack's?

**Comment by guybedford** [comment]
I would rather integrate support for npm postinstall scripts in https://github.com/jspm/npm/issues/36.

**Comment by trusktr** [comment]
:+1:  And what about overriding them in the `jspm` field? I can easily imagine that being needed, as it would be with my package. In npm, it compiles using 6to5, but with jspm, it'll just move files around.

**Comment by trusktr** [comment]
Based on my comments in https://github.com/jspm/npm/issues/36, I think it'd be better to implement it here, so that it can be used with any endpoint, giving jspm users flexibility to choose. jspm doesn't do *exactly* what npm does (all deps in a single folder vs npm's per-package node_modules folders, for example), so jspm doesn't necessarily have to do *exactly* the same with the *scripts*, but it should be optionally be able to. I truly feel that would make it easier to use. `jspm` packages don't have the ability to modify dependencies like `npm` packages can, therefore running scripts 100% of the time will not work 100% of the time.

**Comment by guybedford** [comment]
@trusktr your issue is solved by allowing `directories.lib` in a jspm override.

**Comment by trusktr** [comment]
@guybedford Oh? Did you decide to let `directories.lib` work with `npm:` packages?

Here's a thought! :thought_balloon:  Maybe it shouldn't be the endpoint that determines how things like `directories.lib` and install hooks are treated. It makes sense is to consider whether jspm is being used for the server side vs for the browser.

In the browser, let directories.lib always work. On the server side, ignore directories.lib. Doesn't that seem to make lots of sense? The browser is completely different than server-side nodejs/npm, and can't be treated 100% like nodejs/npm.

**Comment by guybedford** [comment]
@trusktr yes, I am surprised you forgot my admittance you were right and I was wrong so soon on this point. See https://github.com/jspm/npm/issues/35. The idea was to make `directories.lib` be supported only within the `jspm` property, but not at the base level, so we can override npm, but not have any legacy effects creeping in so we retain parity.

**Comment by trusktr** [comment]
@guybedford Oh, I missed that or misunderstood. xD That sounds good.

**Pull request closed without merging**
