### PR TITLE
Add development workflow docs

### PR DESCRIPTION
**Pull request by peteruithoven**
See: https://github.com/jspm/jspm-cli/issues/1109#issuecomment-141371788

### CODE REVIEW

**Comment by guybedford** [comment]
:+1: it would be good to cover the different aspects including server, compilation and caching workflows as well.

**Comment by peteruithoven** [comment]
Definitely! 
But as I'm trying to circumvent compilation steps (with gulp etc) in my development workflow I'm probably not the one to write those.

**Comment by lookfirst** [comment]
@peteruithoven How do you deal with .map files for your code are you just writing everything in ES5?

**Comment by lookfirst** [comment]
There is NO way that bundling would work for me... it is WAY too slow with the number of files that I'm loading. Tens of seconds without minification on and about a minute otherwise. I've got my app split into 4-5 different apps that need individual bundling (and growing constantly)... this wouldn't work at all except for small stuff.

I also don't see the point in skipping the gulp step when bundling is effectively the same thing and you get way more features.

**Comment by peteruithoven** [comment]
I write ES6, `jspm bundle` creates a .map for me. I don't see the problem? 
@lookfirst which part is slow for you? Running the code in the browser or building the bundle? How long it takes to build the dependencies bundle doesn't really matter since you only have to do this after installing or removing dependencies right? I don't have to bundle when changing my own code (during development at least).

**Comment by stoiet** [comment]
Hy! Currently I use 2 commands with exeSync in gulp tasks:
```
jspm bundle source/javascript/**/*.js - [source/javascript/**/*.js] client/dist/bundle-dependency.js --inject --minify --no-runtime --skip-source-maps
jspm bundle  [source/javascript/**/*.js] client/dist/bundle-application.js --inject --no-mangle --inline-source-maps
```

I only watching source/javascript/**/*.js files and re-bundle them with the second command, it would be faster with some caching mechanism, and only use the Builder API for it. With a gulp plugin would be nicer, too.

@lookfirst 's solution seems to better for larger projects, but works only with browserSync.

**Comment by lookfirst** [comment]
I can't imagine doing development without browserSync (you really want to hit reload in the browser every time you change something?!) and size doesn't really matter. =)

**Comment by lookfirst** [comment]
@peteruithoven I don't bundle my dependencies separately. No need with my build system. =)

**Comment by peteruithoven** [comment]
Maybe we can merge these docs and have @lookfirst do a pull request with his approach?

**Comment by guybedford** [comment]
Closing for lack of activity. Feel free to reopen.

**Pull request closed without merging**
