### PR TITLE
Implement #1977: --exact flag for pinning latest version of dependency

### PR DESCRIPTION
**Pull request by joeldenning**
See #1977. The `--exact` flag is intended to be similar to npm's [save-exact](https://docs.npmjs.com/cli/install) flag, where you don't have to specify the version but it still pins the dependency to the latest version.

I saw that you put the discussion label on #1977 and am not sure if that means there was more to talk about before creating a pull request -- if so let me know.

### CODE REVIEW

**Comment by guybedford** [comment]
This looks great, thanks. Yes it would be definitely worth supporting this.

I'm just wondering if it might be nice to also have this work with target versions:

```
jspm install  react@0.14 --exact
```

Where the above will resolve the range, but still pin the exact version into the package.json.

I think that might be something like this path: (although it can probably be better refactored into the conditional)

```javascript
if (!options.parent && options.exact) {
  target.setVersion(resolution.version);
}
```

**Comment by FDiskas** [comment]
:non-potable_water:

**Comment by joeldenning** [comment]
Sounds good -- I have updated the pull request to support `--exact` with target versions (e.g., `jspm install  react@0.14 --exact`)

**Comment by guybedford** [comment]
👍  thanks for your work here!

**Pull request merged**
