### PR TITLE
#1848 - Bundle build not refreshing / updating html files when changed

### PR DESCRIPTION
**Pull request by abhipanda**
Added the wildcard at end of the file URL name to invalidate URL which doesn't match exact URLs

### CODE REVIEW

**Comment by guybedford** [comment]
Are you importing `file.html!text` using plugin syntax?

**Comment by abhipanda** [comment]
Yes that and ng-template. 

`import '../shared/templates/some.tpl.html!ng-template';`

**Comment by guybedford** [comment]
Sure, ok I think we should make this:

```javascript
builder.invalidate(toFileURL(file)); 
builder.invalidate(toFileURL(file) + '!*'); 
```

If that doesn't work though just let me know and we should fix the builder itself to allow this.

**Comment by abhipanda** [comment]
Ok sure I will do that

**Comment by abhipanda** [comment]
@guybedford !* won't work for JS files as they don't have an extension.

**Comment by guybedford** [comment]
@abhipanda yes js files will only catch the `builder.invalidate(toFileURL(file));` case, but by doing both we should always catch the right invalidations.

**Comment by abhipanda** [comment]
Ok so you want both to be there. Don't you think thats redundant - I mean first it will try to get through full name and then with wildcard even though it invalidated the first time.

Doing the wildcard will work for both in one execution. Your call.

**Comment by guybedford** [comment]
Yes exactly, invalidating both is the necessary approach despite redundancy.

**Comment by abhipanda** [comment]
Updated !

**Comment by abhipanda** [comment]
hi @guybedford  is this going to be merged soon ?

**Comment by guybedford** [comment]
@abhipanda apologies, I missed your update comment here. Do you think you could rebase the changes to the branch again for merge?

**Comment by guybedford** [comment]
Included manually in https://github.com/jspm/jspm-cli/commit/fd784241e19d85381ffdf61cc7ad2ad4653dcd68. Thanks for your efforts!

**Comment by abhipanda** [comment]
Oh thanks you @guybedford I was going to do it anyways :)

**Comment by abhipanda** [comment]
Hello @guybedford - when is this fix expected into release ?

**Pull request closed without merging**
