### PR TITLE
Honor existing line endings in config.js

### PR DESCRIPTION
**Pull request by stefanr**
If you are working with an OS that uses different line endings than your config.js, it's pretty annoying that these will be overwritten.

I think it would be nice to honor the existing line endings. This PR will also override the line endings in the package.json depending on the characters used in the config.js, but in my case this is also a nice side effect.

Probably the best approach would be to save the existing line endings somewhere in the corresponding configs (package, loader) and use them explicitly when writing the file.

### CODE REVIEW

**Comment by stefanr** [comment]
Just recognized that this seems to be part of 0.17 ... so ignore this.

**Comment by guybedford** [comment]
Thanks for checking!

**Comment by guybedford** [comment]
Thanks for checking!

**Comment by staxmanade** [comment]
Any thoughts on how can we leverage this? Not following how I can get my line endings to be `\n` instead of `\r\n`?

**Pull request closed without merging**
