### PR TITLE
Explictly mark retriable errors

### PR DESCRIPTION
**Pull request by crisptrutski**
Refs jspm/jspm-cli#718

### CODE REVIEW

**Comment by timbur** [comment]
I'm guessing this is related to the following error I received when using `jspm init`?

```
err  TypeError: Cannot read property 'retriable' of undefined
         at checkRetry (/usr/local/lib/node_modules/jspm/lib/registry.js:139:32)
         at null._onTimeout (/usr/local/lib/node_modules/jspm/lib/registry.js:114:15)
         at Timer.listOnTimeout (timers.js:110:15)
         at timers.js:122:29
         at Immediate._tickCallback [as _onImmediate] (node.js:355:11)
         at processImmediate [as _immediateCallback] (timers.js:358:17)
```

**Comment by crisptrutski** [comment]
Most certainly - hadn't noticed `checkRetry` was used for timeouts. Will patch quickly

**Comment by crisptrutski** [comment]
Addressed in c4bfedf2b98cb492cf5e577cfce58feee6bd4697

**Comment by timbur** [comment]
Awesome, thanks!

**Comment by crisptrutski** [comment]
No problem, sorry for the bug!

**Pull request merged**
