### PR TITLE
JSPM Install should install devDependencies

### LINKED ISSUE #747: JSPM Install should install devDependencies.
`npm install` installs `dependencies` and `devDependencies`.  JSPM should do the same thing when `jspm install` is executed.  When I first checkout a repository, I do not want to have to execute `jspm install` and `jspm install --dev` just to get my repo into a state that I can start working on it.

### PR DESCRIPTION
**Pull request by crisptrutski**
Closes #747

### CODE REVIEW

**Comment by guybedford** [comment]
I'd suggest testing that this doesn't result in all dependencies being saved back into the `dependencies` object.

**Comment by guybedford** [comment]
I think you'll see `traceur` and `babel` have become normal dependencies when doing this.

**Comment by crisptrutski** [comment]
In my testing the behaviour was as expected (existing project, installing new dependencies with and without `--dev`).

How did you test it?

**Comment by guybedford** [comment]
`jspm install` with no arguments.

**Comment by crisptrutski** [comment]
See it, will touch up

**Comment by crisptrutski** [comment]
Came up with a solution, let me know if you're satisfied (unfortunately all four branches can occur)

**Comment by crisptrutski** [comment]
Potentially problematic: can't install different versions to each group, or move dependencies between groups, using `jspm install` with this approach

**Comment by guybedford** [comment]
Commit?

**Comment by crisptrutski** [comment]
Network woes it seems, pushed again

**Comment by guybedford** [comment]
Nice. It seems to look good to me. Let's merge, then I'll do some more testing on master for feedback.

**Pull request merged**
